import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PricePulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-slate-900 border-b border-slate-700">
          <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
            <Link href="/" className="text-2xl font-bold text-white">PricePulse</Link>
            <nav className="space-x-6 text-slate-300 text-sm">
              <Link href="/" className="hover:text-blue-400">Crypto</Link>
              <span className="opacity-50">|</span>
              <Link href="#" className="opacity-50 cursor-not-allowed">Stocks</Link>
              <Link href="#" className="opacity-50 cursor-not-allowed">ETFs</Link>
            </nav>
          </div>
        </header>

        <main>{children}</main>

        <footer className="mt-12 p-4 text-center text-slate-500 text-sm border-t border-slate-700">
          © {new Date().getFullYear()} PricePulse. Built by Jaylin Starlin-Ganaway.
        </footer>
      </body>
    </html>
  );
}
